### PR TITLE
Tweaks to make demo.ipynb work

### PR DESCRIPTION
**Pull request by ErezVolk**
Thank you for making available this really interesting paper and code! I'm trying to work my way through it, and found a couple of minor things missing, which I needed to make the demo run. Hope you find this useful.

The changes are:
- `librosa.output` was removed from the latest librosa
- `synthesis.py` seemed to be missing, so I copied it from AutoCV
- The same for some hparams.
- Support CPU for the rest of us

### CODE REVIEW

**Comment by auspicious3000** [comment]
Thanks for your contribution!

**Comment by mathigatti** [comment]
Just tried it. Works great, thanks!

**Comment by FurkanGozukara** [comment]
@ErezVolk I am getting this error when I run

**Comment by ErezVolk** [comment]
> @ErezVolk I am getting this error when I run
> 
> PS C:\SpeechSplit> python demo.ipynb
> Traceback (most recent call last):
> File "demo.ipynb", line 5, in 
> "execution_count": null,
> NameError: name 'null' is not defined

I may be missing something, but if I don't think you can run `.ipynb` files using command-line Python; you need to run them as a Jupyter notebook.

**Comment by FurkanGozukara** [comment]
> > @ErezVolk I am getting this error when I run
> > PS C:\SpeechSplit> python demo.ipynb
> > Traceback (most recent call last):
> > File "demo.ipynb", line 5, in
> > "execution_count": null,
> > NameError: name 'null' is not defined
> 
> I may be missing something, but if I don't think you can run `.ipynb` files using command-line Python; you need to run them as a Jupyter notebook.

Thank you for reply. 

I run the repo on windows 
I tested train on demo data and it works 

But I have no idea about how to train model on my own wav files and apply trained model to my own wav file 

Could you show me how to do with simple python code?

I am sure it must be easy for you 

E. G. Put train wav files into x folder

Then run this py file 

Then put target wav file into this directory and run this py file

**Comment by FurkanGozukara** [comment]
> > @ErezVolk I am getting this error when I run
> > PS C:\SpeechSplit> python demo.ipynb
> > Traceback (most recent call last):
> > File "demo.ipynb", line 5, in
> > "execution_count": null,
> > NameError: name 'null' is not defined
> 
> I may be missing something, but if I don't think you can run `.ipynb` files using command-line Python; you need to run them as a Jupyter notebook.

my discord username : MonsterMMORPG#2198

my email : furkangozukara@gmail.com

or any other software you use. I would appreciate  a lot if you help me

**Comment by ErezVolk** [comment]
> > > @ErezVolk I am getting this error when I run
> > > PS C:\SpeechSplit> python demo.ipynb
> > > Traceback (most recent call last):
> > > File "demo.ipynb", line 5, in
> > > "execution_count": null,
> > > NameError: name 'null' is not defined
> > 
> > 
> > I may be missing something, but if I don't think you can run `.ipynb` files using command-line Python; you need to run them as a Jupyter notebook.
> 
> my discord username : MonsterMMORPG#2198
> 
> my email : [furkangozukara@gmail.com](mailto:furkangozukara@gmail.com)
> 
> or any other software you use. I would appreciate a lot if you help me

I'm sorry, I'm not the author of this package and I can't really help...

For what it's worth, you can convert the notebook file into a Python script using `jupyter-nbconvert --to python demo.ipynb`; this will create a file called `demo.py` which you should be able to run from the command line. But I haven't actually tried it...

**Comment by FurkanGozukara** [comment]
@ErezVolk thank you for answer

Actually I am trying something else and I am close to achieve

However i need simple help could you check my issue please?

https://github.com/auspicious3000/SpeechSplit/issues/28

**Comment by vlad-i** [comment]
This PR is great! Thanks a lot @ErezVolk

**Comment by cheulyop** [comment]
any reason this pr isn't merged yet? 
i rummaged through issues only to find solutions to all issues in running the demo are in this pr :upside_down_face:

**Review by skol101 — APPROVED** [review]

**Comment by auspicious3000** [comment]
@cheulyop because I am trying to avoid the number of dependencies by replacing librosa with soundfile

**Review by auspicious3000 — CHANGES_REQUESTED** [review]
Thanks for the contribution! In order to minimize the requirement on dependencies, could you please revert back to using soundfile instead of librosa in demo.ipynb?

**Comment by cheulyop** [comment]
@auspicious3000 but doesn't librosa already use soundfile for i/o?
see https://librosa.org/doc/main/ioformats.html

**Comment by auspicious3000** [comment]
> @auspicious3000 but doesn't librosa already use soundfile for i/o? see https://librosa.org/doc/main/ioformats.html

We are trying to minimize the requirement on dependencies.
Librosa has more dependencies, such as a certain version of numpy, and thus cannot be properly installed on some platforms. Since we are only reading and writing wav files, using librosa is overkill.

**Comment by cheulyop** [comment]
@auspicious3000 I think there was some misunderstanding 🙂 
The original code was using librosa,
and this PR suggested using soundfile instead, as `librosa.output` was deprecated.

**Pull request merged**
